
name: Build and Release Electron App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # 当推送 v* 格式的标签时触发发布
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub Token，用于上传发布资产
          github_token: ${{ secrets.github_token }}
          
          # 如果当前提交是标签（如 v1.0.0），则执行发布操作
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          
          # 可选：指定构建脚本名称，默认为 build
          # build_script_name: build
          
          # 可选：跳过构建脚本，直接运行 electron-builder
          # skip_build: false
          
          # 可选：传递给 electron-builder 的额外参数
          # args: --publish always
