
name: 编译生成二进制文件

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:

      - name: 设置环境变量
        shell: cmd
        run: |
          setx DEPOT_TOOLS_WIN_TOOLCHAIN 0
          setx GIT_CACHE_PATH %userprofile%\.git_cache
          git config --global core.filemode false
          git config --global core.autocrlf false
          git config --global branch.autosetuprebase always
          git config --global core.fscache true
          git config --global core.preloadindex true
          git config --global core.longpaths true
          md ..\root
          cd ..\root
          setx CHROMIUM_BUILDTOOLS_PATH %cd%\buildtools

      - name: 显示当前目录
        shell: cmd
        run: |
          echo %GIT_CACHE_PATH%
          if not exist "%GIT_CACHE_PATH%" md "%GIT_CACHE_PATH%"
          cd
          dir

      - name: 安装 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: 安装编译工具
        run: |
          npm install -g @electron/build-tools

      - name: 检出代码
        run: |
          gclient config --name "src/electron" --unmanaged https://github.com/yunxu1019/electron-22.3.27
          gclient sync --with_branch_heads --with_tags
          cd src/electron
          git pull
          gclient sync -f

      - name: 编译
        run: |
          gn gen out/Release --args="import(\"//electron/build/args/release.gn\")"

      # - name: 安装依赖
      #   run: |
      #     npm install -g yarn
      #     yarn install --frozen-lockfile

      - name: 看看当前目录都有些什么
        run: |
          cd
          dir
          dir out
          dir chromium_src
        shell: cmd

      # - name: 上传到 Github Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: electron-build-output
      #     path: src/out/Testing # 根据实际构建输出路径调整
      #     retention-days: 2

